dist: xenial   # required for Python >= 3.7
language: python
rvm:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.TXT
# command to run tests
# before_script:
#   - root_env.py
# import:
#   - source: root_env.yml
before_install:
  - source root/bin/thisroot.sh
script:
  - echo "TODO"
  - pytest
os:
  - linux
