# dist: xenial   # required for Python >= 3.7
dist: focal # For Ubuntu20.04
language:
  - python
  - cpp
python:
  - "3.8.10"
# command to install dependencies
install:
  - pip install -r requirements.TXT

before_install:
# ROOT install
  - wget https://root.cern/download/root_v6.24.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
  - tar xzf root_v6.24.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
  - source root/bin/thisroot.sh

# command to run tests
script:
  - echo "TODO"
  - pytest
os:
  - linux
