dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.TXT
# command to run tests
# before_script:
#   - root_env.py
# import:
#   - source: root_env.yml
before_install:
  # - wget https://root.cern/download/root_v6.24.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
  # - tar xzf root_v6.24.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
  - wget https://root.cern/download/root_v6.24.06.source.tar.gz
  - tar xzf root_v6.24.06.source.tar.gz
  - source root/bin/thisroot.sh
script:
  - echo "TODO"
  - pytest
os:
  - linux
